
import { User, Skill, Message, Post, Product } from './types';

export const SKILLS: Skill[] = [
  { id: 1, name: 'React' },
  { id: 2, name: 'Guitar' },
  { id: 3, name: 'Python' },
  { id: 4, name: 'Italian Cooking' },
  { id: 5, name: 'Data Science' },
  { id: 6, name: 'UI/UX Design' },
  { id: 7, name: 'Photography' },
  { id: 8, name: 'Creative Writing' },
  { id: 9, name: 'Public Speaking' },
  { id: 10, name: 'Sourdough Baking' },
];

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: 'Alex Doe',
    avatar: 'https://picsum.photos/seed/alex/200',
    bio: 'Frontend developer by day, aspiring chef by night. I love building beautiful UIs and perfecting my pasta sauce. Let\'s connect and learn together!',
    skillsToTeach: [SKILLS[0], SKILLS[5]],
    skillsToLearn: [SKILLS[3], SKILLS[9]],
    matches: [2, 4],
    status: 'online',
    level: 5,
    xp: 45,
    badges: ['React Pro', 'UI Guru', 'First Match'],
    streak: 3,
    linkedinUrl: 'https://www.linkedin.com/in/alex-doe-example',
  },
  {
    id: 2,
    name: 'Brenda Smith',
    avatar: 'https://picsum.photos/seed/brenda/200',
    bio: 'Passionate about food and culture. I can teach you how to make authentic gnocchi and would love to learn how to build a simple website for my recipes.',
    skillsToTeach: [SKILLS[3], SKILLS[9]],
    skillsToLearn: [SKILLS[0]],
    matches: [1],
    status: 'online',
    level: 4,
    xp: 80,
    badges: ['Pasta Master', 'Baker'],
    streak: 2,
  },
  {
    id: 3,
    name: 'Charlie Brown',
    avatar: 'https://picsum.photos/seed/charlie/200',
    bio: 'Data scientist who finds stories in numbers. I can help you with Python and machine learning concepts. Looking to pick up a creative hobby like guitar.',
    skillsToTeach: [SKILLS[2], SKILLS[4]],
    skillsToLearn: [SKILLS[1], SKILLS[6]],
    matches: [],
    status: 'offline',
    level: 2,
    xp: 10,
    badges: ['Pythonista', 'Newbie'],
    streak: 0,
    linkedinUrl: 'https://www.linkedin.com/in/charlie-brown-example',
  },
  {
    id: 4,
    name: 'Diana Prince',
    avatar: 'https://picsum.photos/seed/diana/200',
    bio: 'Musician and writer. I can teach you the basics of acoustic guitar. I\'m interested in learning how to analyze music trends with data science.',
    skillsToTeach: [SKILLS[1], SKILLS[7]],
    skillsToLearn: [SKILLS[4]],
    matches: [1],
    status: 'online',
    level: 6,
    xp: 20,
    badges: ['Guitar Hero', 'Top Teacher'],
    streak: 5,
  },
  {
    id: 5,
    name: 'Ethan Hunt',
    avatar: 'https://picsum.photos/seed/ethan/200',
    bio: 'Photographer and public speaker. I can teach you how to capture stunning portraits. I want to learn creative writing to tell better stories with my photos.',
    skillsToTeach: [SKILLS[6], SKILLS[8]],
    skillsToLearn: [SKILLS[7]],
    matches: [],
    status: 'offline',
    level: 3,
    xp: 75,
    badges: ['Photographer', 'Speaker'],
    streak: 1,
    linkedinUrl: 'https://www.linkedin.com/in/ethan-hunt-example',
  },
   {
    id: 6,
    name: 'Fiona Glenanne',
    avatar: 'https://picsum.photos/seed/fiona/200',
    bio: 'Writer and artist. I can help you with creative writing prompts and techniques. I\'m looking to learn Python to create interactive stories.',
    skillsToTeach: [SKILLS[7]],
    skillsToLearn: [SKILLS[2]],
    matches: [],
    status: 'offline',
    level: 1,
    xp: 5,
    badges: ['Newbie'],
    streak: 0,
  },
  {
    id: 7,
    name: 'George King',
    avatar: 'https://picsum.photos/seed/george/200',
    bio: "Public speaking coach helping people find their voice. In my free time, I'm trying to become a better photographer.",
    skillsToTeach: [SKILLS[8]],
    skillsToLearn: [SKILLS[6]],
    matches: [],
    status: 'online',
    level: 7,
    xp: 60,
    badges: ['Orator', 'Motivator'],
    streak: 4,
  },
  {
    id: 8,
    name: 'Hannah Montana',
    avatar: 'https://picsum.photos/seed/hannah/200',
    bio: "Creative writer and novelist. I can help you craft compelling stories. I want to learn React to build a website for my portfolio.",
    skillsToTeach: [SKILLS[7]],
    skillsToLearn: [SKILLS[0]],
    matches: [],
    status: 'offline',
    level: 3,
    xp: 25,
    badges: ['Storyteller'],
    streak: 0,
  },
  {
    id: 9,
    name: 'Ian Fleming',
    avatar: 'https://picsum.photos/seed/ian/200',
    bio: "Python wizard and data geek. I can automate anything! Looking to unwind by learning to play the guitar.",
    skillsToTeach: [SKILLS[2]],
    skillsToLearn: [SKILLS[1]],
    matches: [],
    status: 'online',
    level: 8,
    xp: 90,
    badges: ['Python Pro', 'Data Ninja'],
    streak: 10,
    linkedinUrl: 'https://www.linkedin.com/in/ian-fleming-example',
  },
  {
    id: 10,
    name: 'Jane Austen',
    avatar: 'https://picsum.photos/seed/jane/200',
    bio: "Passionate home baker specializing in sourdough. Let's bake together! I'm hoping to improve my public speaking skills for workshops.",
    skillsToTeach: [SKILLS[9]],
    skillsToLearn: [SKILLS[8]],
    matches: [],
    status: 'online',
    level: 5,
    xp: 15,
    badges: ['Artisan Baker', 'Starter Whisperer'],
    streak: 3,
  },
  {
    id: 11,
    name: 'Kevin McCallister',
    avatar: 'https://picsum.photos/seed/kevin/200',
    bio: "UI/UX designer with a passion for clean interfaces. I can teach you Figma and design principles. I want to learn Italian cooking for a trip to Italy!",
    skillsToTeach: [SKILLS[5]],
    skillsToLearn: [SKILLS[3]],
    matches: [],
    status: 'offline',
    level: 4,
    xp: 50,
    badges: ['Pixel Perfect', 'Design Thinker'],
    streak: 1,
  },
  {
    id: 12,
    name: 'Laura Croft',
    avatar: 'https://picsum.photos/seed/laura/200',
    bio: "Adventurous photographer capturing landscapes around the world. I can teach you everything from composition to editing. Eager to learn data science to analyze photo trends.",
    skillsToTeach: [SKILLS[6]],
    skillsToLearn: [SKILLS[4]],
    matches: [],
    status: 'online',
    level: 9,
    xp: 70,
    badges: ['Globetrotter', 'Top Photographer'],
    streak: 8,
    linkedinUrl: 'https://www.linkedin.com/in/laura-croft-example',
  },
  {
    id: 13,
    name: 'Mike Ross',
    avatar: 'https://picsum.photos/seed/mike/200',
    bio: "Aspiring writer looking for a mentor in creative writing. I'm a quick learner and can teach you the basics of Python.",
    skillsToTeach: [SKILLS[2]],
    skillsToLearn: [SKILLS[7]],
    matches: [],
    status: 'online',
    level: 2,
    xp: 30,
    badges: ['Newbie Coder'],
    streak: 1,
  },
  {
    id: 14,
    name: 'Nancy Drew',
    avatar: 'https://picsum.photos/seed/nancy/200',
    bio: "Data scientist who loves solving puzzles with code. I'm looking to learn UI/UX design to make my data visualizations more impactful.",
    skillsToTeach: [SKILLS[4]],
    skillsToLearn: [SKILLS[5]],
    matches: [],
    status: 'offline',
    level: 6,
    xp: 40,
    badges: ['Data Detective', 'ML Enthusiast'],
    streak: 2,
  },
  {
    id: 15,
    name: 'Oscar Wilde',
    avatar: 'https://picsum.photos/seed/oscar/200',
    bio: "I make a mean carbonara and can teach you the secrets of Italian cuisine. I'd love to learn how to play some simple tunes on the guitar.",
    skillsToTeach: [SKILLS[3]],
    skillsToLearn: [SKILLS[1]],
    matches: [],
    status: 'online',
    level: 3,
    xp: 85,
    badges: ['Chef'],
    streak: 2,
    linkedinUrl: 'https://www.linkedin.com/in/oscar-wilde-example',
  },
  {
    id: 16,
    name: 'Penny Lane',
    avatar: 'https://picsum.photos/seed/penny/200',
    bio: "React developer building cool web apps. I can help you get started with modern frontend development. Looking to improve my photography skills for my travel blog.",
    skillsToTeach: [SKILLS[0]],
    skillsToLearn: [SKILLS[6]],
    matches: [],
    status: 'online',
    level: 5,
    xp: 55,
    badges: ['React Rockstar'],
    streak: 6,
  },
];

export const MOCK_MESSAGES: Record<number, Message[]> = {
  2: [
    { id: 1, senderId: 2, receiverId: 1, text: "Hey Alex! I saw we matched. Your React skills are exactly what I need for my recipe blog.", timestamp: "2023-10-27T10:00:00Z" },
    { id: 2, senderId: 1, receiverId: 2, text: "Hi Brenda! Awesome. And I've been dying to learn how to make proper pasta. This is a perfect match!", timestamp: "2023-10-27T10:01:00Z", reaction: '🎉' },
    { id: 3, senderId: 2, receiverId: 1, text: "Great! When are you free to chat about it?", timestamp: "2023-10-27T10:02:00Z" },
  ],
  4: [
    { id: 4, senderId: 4, receiverId: 1, text: "Hi! I see you're looking for data science help. I'd love to learn some photography.", timestamp: "2023-10-27T11:00:00Z" },
  ]
};

export const MOCK_POSTS: Post[] = [
    { id: 1, authorId: 4, thumbnailUrl: 'https://picsum.photos/seed/guitarpost/600/400', caption: 'Just learned a new riff on the guitar! Who wants to learn it with me? 🎸 #guitar #music', likes: 125, comments: 12 },
    { id: 2, authorId: 2, thumbnailUrl: 'https://picsum.photos/seed/pastapost/600/400', caption: 'The perfect sourdough loaf doesn\'t exi-- 😍. So proud of this one! #baking #sourdough', likes: 340, comments: 28 },
    { id: 3, authorId: 5, thumbnailUrl: 'https://picsum.photos/seed/photopost/600/400', caption: 'Golden hour is magic hour for portraits. Here\'s a shot from my latest session. #photography #portraits', likes: 210, comments: 19 },
    { id: 4, authorId: 1, thumbnailUrl: 'https://picsum.photos/seed/reactpost/600/400', caption: 'Working on a new component library in React. The developer experience is 🔥. #reactdev #coding', likes: 450, comments: 55 },
];

export const MOCK_PRODUCTS: Product[] = [
    { id: 1, name: 'Professional React Hooks Course', imageUrl: 'https://picsum.photos/seed/reactkit/200', price: '$49.99', skillId: 1, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE1' },
    { id: 2, name: 'Acoustic Guitar Starter Pack', imageUrl: 'https://picsum.photos/seed/guitarkit/200', price: '$129.99', skillId: 2, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE2' },
    { id: 3, name: 'Authentic Pasta Making Kit', imageUrl: 'https://picsum.photos/seed/pastakit/200', price: '$39.99', skillId: 4, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE3' },
    { id: 4, name: 'Sourdough Starter Kit', imageUrl: 'https://picsum.photos/seed/bakingkit/200', price: '$24.99', skillId: 10, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE4' },
    { id: 5, name: 'DSLR Camera for Beginners', imageUrl: 'https://picsum.photos/seed/camerakit/200', price: '$499.99', skillId: 7, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE5' },
];
