import { User, Skill, Message, Post, Product } from './types';

export const SKILLS: Skill[] = [
  { id: 1, name: 'React' },
  { id: 2, name: 'Guitar' },
  { id: 3, name: 'Python' },
  { id: 4, name: 'Italian Cooking' },
  { id: 5, name: 'Data Science' },
  { id: 6, name: 'UI/UX Design' },
  { id: 7, name: 'Photography' },
  { id: 8, name: 'Creative Writing' },
  { id: 9, name: 'Public Speaking' },
  { id: 10, name: 'Sourdough Baking' },
  { id: 11, name: 'Digital Marketing' },
  { id: 12, name: 'Yoga Instruction' },
  { id: 13, name: 'French Language' },
  { id: 14, name: 'Video Editing' },
  { id: 15, name: 'Project Management' },
  { id: 16, name: 'Chess Strategy' },
  { id: 17, name: 'Personal Finance' },
  { id: 18, name: 'Knitting' },
  { id: 19, name: 'Gardening' },
  { id: 20, name: 'SEO Optimization' },
];

const today = new Date();
const getTodayAtTime = (hour: number, minute: number = 0) => {
    const d = new Date(today);
    d.setHours(hour, minute, 0, 0);
    return d.toISOString();
}

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: 'Aditi Sharma',
    avatar: 'https://ui-avatars.com/api/?name=Aditi+Sharma&background=random&color=fff&size=200',
    bio: 'Frontend developer by day, aspiring chef by night. I love building beautiful UIs and perfecting my pasta sauce. Let\'s connect and learn together!',
    skillsToTeach: [{ ...SKILLS[0], proficiency: 3 }, { ...SKILLS[5], proficiency: 2 }],
    skillsToLearn: [SKILLS[3], SKILLS[9], SKILLS[12], SKILLS[6]],
    matches: [
      { userId: 2, status: 'in-progress', scheduledSession: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString() },
      { userId: 4, status: 'completed', scheduledSession: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), rating: 5 },
      { userId: 17, status: 'not-started', scheduledSession: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() },
      { userId: 5, status: 'in-progress', scheduledSession: getTodayAtTime(10) },
      { userId: 16, status: 'in-progress', scheduledSession: getTodayAtTime(14) },
      { userId: 33, status: 'in-progress', scheduledSession: getTodayAtTime(16, 30) },
      { userId: 9, status: 'not-started', sessionProposal: { proposerId: 1, date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), status: 'pending' } },
      { userId: 12, status: 'not-started', sessionProposal: { proposerId: 12, date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), status: 'pending' } },
      { userId: 13, status: 'in-progress', scheduledSession: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString() },
      { userId: 15, status: 'not-started', scheduledSession: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() },
      { userId: 19, status: 'in-progress', scheduledSession: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString() },
      { userId: 22, status: 'not-started', scheduledSession: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString() },
      { userId: 28, status: 'in-progress', scheduledSession: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString() },
      { userId: 10, status: 'not-started', scheduledSession: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    status: 'online',
    level: 5,
    xp: 45,
    badges: ['React Pro', 'UI Guru', 'First Match', 'First Lesson', 'Curious Learner', 'Consistent', 'Social Butterfly'],
    streak: 3,
    verifiedSkills: [1],
    linkedinUrl: 'https://www.linkedin.com/in/aditi-sharma-example',
    teacherRating: 4.0,
    totalRatings: 1,
  },
  {
    id: 2,
    name: 'Rohan Verma',
    avatar: 'https://ui-avatars.com/api/?name=Rohan+Verma&background=random&color=fff&size=200',
    bio: 'Passionate about food and culture. I can teach you how to make authentic gnocchi and would love to learn how to build a simple website for my recipes.',
    skillsToTeach: [{ ...SKILLS[3], proficiency: 3 }, { ...SKILLS[9], proficiency: 2 }],
    skillsToLearn: [SKILLS[0]],
    matches: [{ userId: 1, status: 'in-progress', scheduledSession: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString() }],
    status: 'online',
    level: 4,
    xp: 80,
    badges: ['Pasta Master', 'Baker', 'First Match', 'First Lesson', 'Curious Learner'],
    streak: 2,
    verifiedSkills: [4, 10],
    teacherRating: 0,
    totalRatings: 0,
  },
  {
    id: 3,
    name: 'Priya Patel',
    avatar: 'https://ui-avatars.com/api/?name=Priya+Patel&background=random&color=fff&size=200',
    bio: 'Data scientist who finds stories in numbers. I can help you with Python and machine learning concepts. Looking to pick up a creative hobby like guitar.',
    skillsToTeach: [{ ...SKILLS[2], proficiency: 3 }, { ...SKILLS[4], proficiency: 2 }],
    skillsToLearn: [SKILLS[1], SKILLS[6]],
    matches: [{ userId: 21, status: 'completed' }],
    status: 'offline',
    level: 2,
    xp: 10,
    badges: ['Pythonista', 'Newbie', 'First Lesson', 'Curious Learner'],
    streak: 0,
    verifiedSkills: [3],
    linkedinUrl: 'https://www.linkedin.com/in/priya-patel-example',
    teacherRating: 4.8,
    totalRatings: 12,
  },
  {
    id: 4,
    name: 'Vikram Singh',
    avatar: 'https://ui-avatars.com/api/?name=Vikram+Singh&background=random&color=fff&size=200',
    bio: 'Musician and writer. I can teach you the basics of acoustic guitar. I\'m interested in learning how to analyze music trends with data science.',
    skillsToTeach: [{ ...SKILLS[1], proficiency: 2 }, { ...SKILLS[7], proficiency: 3 }],
    skillsToLearn: [SKILLS[4]],
    matches: [{ userId: 1, status: 'completed', scheduledSession: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), rating: 4 }],
    status: 'online',
    level: 6,
    xp: 20,
    badges: ['Guitar Hero', 'Top Teacher', 'First Match', 'First Lesson', 'Curious Learner', 'Consistent'],
    streak: 5,
    verifiedSkills: [2],
    teacherRating: 5.0,
    totalRatings: 1,
  },
  {
    id: 5,
    name: 'Anjali Mehta',
    avatar: 'https://ui-avatars.com/api/?name=Anjali+Mehta&background=random&color=fff&size=200',
    bio: 'Photographer and public speaker. I can teach you how to capture stunning portraits. I want to learn creative writing to tell better stories with my photos.',
    skillsToTeach: [{ ...SKILLS[6], proficiency: 3 }, { ...SKILLS[8], proficiency: 2 }],
    skillsToLearn: [SKILLS[7]],
    matches: [
        { userId: 25, status: 'in-progress' },
        { userId: 1, status: 'in-progress', scheduledSession: getTodayAtTime(10) }
    ],
    status: 'offline',
    level: 3,
    xp: 75,
    badges: ['Photographer', 'Speaker', 'First Lesson', 'Curious Learner'],
    streak: 1,
    verifiedSkills: [],
    linkedinUrl: 'https://www.linkedin.com/in/anjali-mehta-example',
    teacherRating: 4.6,
    totalRatings: 8,
  },
   {
    id: 6,
    name: 'Sameer Desai',
    avatar: 'https://ui-avatars.com/api/?name=Sameer+Desai&background=random&color=fff&size=200',
    bio: 'Writer and artist. I can help you with creative writing prompts and techniques. I\'m looking to learn Python to create interactive stories.',
    skillsToTeach: [{ ...SKILLS[7], proficiency: 2 }],
    skillsToLearn: [SKILLS[2]],
    matches: [],
    status: 'offline',
    level: 1,
    xp: 5,
    badges: ['Newbie', 'First Lesson', 'Curious Learner'],
    streak: 0,
    verifiedSkills: [],
  },
  {
    id: 7,
    name: 'Neha Gupta',
    avatar: 'https://ui-avatars.com/api/?name=Neha+Gupta&background=random&color=fff&size=200',
    bio: "Public speaking coach helping people find their voice. In my free time, I'm trying to become a better photographer.",
    skillsToTeach: [{ ...SKILLS[8], proficiency: 3 }],
    skillsToLearn: [SKILLS[6]],
    matches: [],
    status: 'online',
    level: 7,
    xp: 60,
    badges: ['Orator', 'Motivator', 'First Lesson', 'Curious Learner', 'Consistent'],
    streak: 4,
    verifiedSkills: [9],
    teacherRating: 4.9,
    totalRatings: 25,
  },
  {
    id: 8,
    name: 'Arjun Reddy',
    avatar: 'https://ui-avatars.com/api/?name=Arjun+Reddy&background=random&color=fff&size=200',
    bio: "Creative writer and novelist. I can help you craft compelling stories. I want to learn React to build a website for my portfolio.",
    skillsToTeach: [{ ...SKILLS[7], proficiency: 2 }],
    skillsToLearn: [SKILLS[0]],
    matches: [],
    status: 'offline',
    level: 3,
    xp: 25,
    badges: ['Storyteller', 'First Lesson', 'Curious Learner'],
    streak: 0,
    verifiedSkills: [],
  },
  {
    id: 9,
    name: 'Kavya Rao',
    avatar: 'https://ui-avatars.com/api/?name=Kavya+Rao&background=random&color=fff&size=200',
    bio: "Python wizard and data geek. I can automate anything! Looking to unwind by learning to play the guitar.",
    skillsToTeach: [{ ...SKILLS[2], proficiency: 3 }],
    skillsToLearn: [SKILLS[1]],
    matches: [{ userId: 1, status: 'not-started', sessionProposal: { proposerId: 1, date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), status: 'pending' } }],
    status: 'online',
    level: 8,
    xp: 90,
    badges: ['Python Pro', 'Data Ninja', 'First Lesson', 'Curious Learner', 'Dedicated', 'Unstoppable', 'Super Connector'],
    streak: 10,
    verifiedSkills: [3],
    linkedinUrl: 'https://www.linkedin.com/in/kavya-rao-example',
    teacherRating: 4.7,
    totalRatings: 15,
  },
  {
    id: 10,
    name: 'Harish Kumar',
    avatar: 'https://ui-avatars.com/api/?name=Harish+Kumar&background=random&color=fff&size=200',
    bio: "Passionate home baker specializing in sourdough. Let's bake together! I'm hoping to improve my public speaking skills for workshops.",
    skillsToTeach: [{ ...SKILLS[9], proficiency: 3 }],
    skillsToLearn: [SKILLS[8]],
    matches: [
        { userId: 1, status: 'not-started', scheduledSession: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString() }
    ],
    status: 'online',
    level: 5,
    xp: 15,
    badges: ['Artisan Baker', 'Starter Whisperer', 'First Lesson', 'Curious Learner', 'Consistent'],
    streak: 3,
    verifiedSkills: [10],
  },
  {
    id: 11,
    name: 'Sunita Joshi',
    avatar: 'https://ui-avatars.com/api/?name=Sunita+Joshi&background=random&color=fff&size=200',
    bio: "UI/UX designer with a passion for clean interfaces. I can teach you Figma and design principles. I want to learn Italian cooking for a trip to Italy!",
    skillsToTeach: [{ ...SKILLS[5], proficiency: 2 }],
    skillsToLearn: [SKILLS[3]],
    matches: [],
    status: 'offline',
    level: 4,
    xp: 50,
    badges: ['Pixel Perfect', 'Design Thinker', 'First Lesson', 'Curious Learner'],
    streak: 1,
    verifiedSkills: [6],
  },
  {
    id: 12,
    name: 'Rajesh Nair',
    avatar: 'https://ui-avatars.com/api/?name=Rajesh+Nair&background=random&color=fff&size=200',
    bio: "Adventurous photographer capturing landscapes around the world. I can teach you everything from composition to editing. Eager to learn data science to analyze photo trends.",
    skillsToTeach: [{ ...SKILLS[6], proficiency: 3 }],
    skillsToLearn: [SKILLS[4]],
    matches: [{ userId: 1, status: 'not-started', sessionProposal: { proposerId: 12, date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), status: 'pending' } }],
    status: 'online',
    level: 9,
    xp: 70,
    badges: ['Globetrotter', 'Top Photographer', 'First Lesson', 'Curious Learner', 'Dedicated'],
    streak: 8,
    verifiedSkills: [7],
    linkedinUrl: 'https://www.linkedin.com/in/rajesh-nair-example',
    teacherRating: 5.0,
    totalRatings: 3,
  },
  {
    id: 13,
    name: 'Meera Iyer',
    avatar: 'https://ui-avatars.com/api/?name=Meera+Iyer&background=random&color=fff&size=200',
    bio: "Aspiring writer looking for a mentor in creative writing. I'm a quick learner and can teach you the basics of Python.",
    skillsToTeach: [{ ...SKILLS[2], proficiency: 1 }],
    skillsToLearn: [SKILLS[7]],
    matches: [{ userId: 1, status: 'in-progress', scheduledSession: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString() }],
    status: 'online',
    level: 2,
    xp: 30,
    badges: ['Newbie Coder', 'First Lesson', 'Curious Learner'],
    streak: 1,
    verifiedSkills: [],
  },
  {
    id: 14,
    name: 'Suresh Menon',
    avatar: 'https://ui-avatars.com/api/?name=Suresh+Menon&background=random&color=fff&size=200',
    bio: "Data scientist who loves solving puzzles with code. I'm looking to learn UI/UX design to make my data visualizations more impactful.",
    skillsToTeach: [{ ...SKILLS[4], proficiency: 2 }],
    skillsToLearn: [SKILLS[5]],
    matches: [],
    status: 'offline',
    level: 6,
    xp: 40,
    badges: ['Data Detective', 'ML Enthusiast', 'First Lesson', 'Curious Learner'],
    streak: 2,
    verifiedSkills: [5],
  },
  {
    id: 15,
    name: 'Lakshmi Pillai',
    avatar: 'https://ui-avatars.com/api/?name=Lakshmi+Pillai&background=random&color=fff&size=200',
    bio: "I make a mean carbonara and can teach you the secrets of Italian cuisine. I'd love to learn how to play some simple tunes on the guitar.",
    skillsToTeach: [{ ...SKILLS[3], proficiency: 2 }],
    skillsToLearn: [SKILLS[1]],
    matches: [{ userId: 1, status: 'not-started', scheduledSession: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() }],
    status: 'online',
    level: 3,
    xp: 85,
    badges: ['Chef', 'First Lesson', 'Curious Learner'],
    streak: 2,
    verifiedSkills: [],
    linkedinUrl: 'https://www.linkedin.com/in/lakshmi-pillai-example',
  },
  {
    id: 16,
    name: 'Arnav Choudhary',
    avatar: 'https://ui-avatars.com/api/?name=Arnav+Choudhary&background=random&color=fff&size=200',
    bio: "React developer building cool web apps. I can help you get started with modern frontend development. Looking to improve my photography skills for my travel blog.",
    skillsToTeach: [{ ...SKILLS[0], proficiency: 2 }],
    skillsToLearn: [SKILLS[6]],
    matches: [{ userId: 1, status: 'in-progress', scheduledSession: getTodayAtTime(14) }],
    status: 'online',
    level: 5,
    xp: 55,
    badges: ['React Rockstar', 'First Lesson', 'Curious Learner', 'Consistent'],
    streak: 6,
    verifiedSkills: [1],
    teacherRating: 4.5,
    totalRatings: 4,
  },
  {
    id: 17,
    name: 'Divya Agarwal',
    avatar: 'https://ui-avatars.com/api/?name=Divya+Agarwal&background=random&color=fff&size=200',
    bio: 'Yoga instructor and mindfulness coach. Let\'s find our balance. I would love to learn how to create engaging video content for my classes.',
    skillsToTeach: [{ ...SKILLS[11], proficiency: 3 }],
    skillsToLearn: [SKILLS[13]],
    matches: [{ userId: 1, status: 'not-started', scheduledSession: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() }],
    status: 'online',
    level: 3,
    xp: 40,
    badges: ['Mindful Master', 'First Lesson', 'Curious Learner', 'First Match'],
    streak: 1,
    verifiedSkills: [12],
    linkedinUrl: 'https://www.linkedin.com/in/divya-agarwal-example',
  },
  {
    id: 18,
    name: 'Mohan Krishnan',
    avatar: 'https://ui-avatars.com/api/?name=Mohan+Krishnan&background=random&color=fff&size=200',
    bio: 'Digital marketing strategist. I can teach you SEO and social media marketing. I want to learn French for an upcoming trip to Paris.',
    skillsToTeach: [{ ...SKILLS[10], proficiency: 3 }, { ...SKILLS[19], proficiency: 2 }],
    skillsToLearn: [SKILLS[12]],
    matches: [{ userId: 19, status: 'in-progress' }],
    status: 'offline',
    level: 7,
    xp: 20,
    badges: ['Marketing Guru', 'SEO Pro', 'First Lesson', 'Curious Learner', 'Dedicated'],
    streak: 8,
    verifiedSkills: [11, 20],
  },
  {
    id: 19,
    name: 'Sita Ramachandran',
    avatar: 'https://ui-avatars.com/api/?name=Sita+Ramachandran&background=random&color=fff&size=200',
    bio: 'Native French speaker and language tutor. Let\'s practice your conversational French! I\'m looking to improve my digital marketing skills.',
    skillsToTeach: [{ ...SKILLS[12], proficiency: 3 }],
    skillsToLearn: [SKILLS[10]],
    matches: [{ userId: 1, status: 'in-progress', scheduledSession: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString() }, { userId: 18, status: 'in-progress' }],
    status: 'online',
    level: 5,
    xp: 50,
    badges: ['Francophone', 'First Lesson', 'Curious Learner', 'Consistent'],
    streak: 4,
    verifiedSkills: [13],
  },
  {
    id: 20,
    name: 'Gopal Subramanian',
    avatar: 'https://ui-avatars.com/api/?name=Gopal+Subramanian&background=random&color=fff&size=200',
    bio: 'Project manager with Agile certification. I can help you organize your projects. I want to learn chess to improve my strategic thinking.',
    skillsToTeach: [{ ...SKILLS[14], proficiency: 3 }],
    skillsToLearn: [SKILLS[15]],
    matches: [],
    status: 'online',
    level: 6,
    xp: 10,
    badges: ['Agile Master', 'Scrum Pro', 'First Lesson', 'Curious Learner'],
    streak: 2,
    verifiedSkills: [15],
  },
  {
    id: 21,
    name: 'Ishita Bhattacharya',
    avatar: 'https://ui-avatars.com/api/?name=Ishita+Bhattacharya&background=random&color=fff&size=200',
    bio: 'Chess enthusiast and club player. I can teach you openings and endgames. I\'m interested in data science to analyze my games.',
    skillsToTeach: [{ ...SKILLS[15], proficiency: 2 }],
    skillsToLearn: [SKILLS[4]],
    matches: [{ userId: 3, status: 'completed' }],
    status: 'offline',
    level: 4,
    xp: 90,
    badges: ['Chess Master', 'First Lesson', 'Curious Learner'],
    streak: 1,
    verifiedSkills: [],
  },
  {
    id: 22,
    name: 'Kiran Bedi',
    avatar: 'https://ui-avatars.com/api/?name=Kiran+Bedi&background=random&color=fff&size=200',
    bio: 'Financial advisor helping people with budgeting and investing. I can teach you the basics of personal finance. Looking to learn gardening to relax.',
    skillsToTeach: [{ ...SKILLS[16], proficiency: 3 }],
    skillsToLearn: [SKILLS[18]],
    matches: [{ userId: 1, status: 'not-started', scheduledSession: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString() }, { userId: 23, status: 'not-started' }],
    status: 'online',
    level: 8,
    xp: 30,
    badges: ['Finance Whiz', 'First Lesson', 'Curious Learner', 'Unstoppable'],
    streak: 15,
    verifiedSkills: [17],
  },
  {
    id: 23,
    name: 'Deepak Chopra',
    avatar: 'https://ui-avatars.com/api/?name=Deepak+Chopra&background=random&color=fff&size=200',
    bio: 'I have a green thumb and can teach you all about urban gardening. I\'d love to get my personal finances in order.',
    skillsToTeach: [{ ...SKILLS[18], proficiency: 2 }],
    skillsToLearn: [SKILLS[16]],
    matches: [{ userId: 22, status: 'not-started' }],
    status: 'online',
    level: 3,
    xp: 60,
    badges: ['Gardener', 'Green Thumb', 'First Lesson', 'Curious Learner'],
    streak: 2,
    verifiedSkills: [19],
  },
  {
    id: 24,
    name: 'Padma Lakshmi',
    avatar: 'https://ui-avatars.com/api/?name=Padma+Lakshmi&background=random&color=fff&size=200',
    bio: 'I can knit anything from scarves to sweaters. Let me teach you! I want to learn video editing to create tutorials.',
    skillsToTeach: [{ ...SKILLS[17], proficiency: 2 }],
    skillsToLearn: [SKILLS[13]],
    matches: [],
    status: 'offline',
    level: 2,
    xp: 70,
    badges: ['Knitting Pro', 'First Lesson', 'Curious Learner'],
    streak: 0,
    verifiedSkills: [],
  },
  {
    id: 25,
    name: 'Nandita Das',
    avatar: 'https://ui-avatars.com/api/?name=Nandita+Das&background=random&color=fff&size=200',
    bio: 'Video editor for a small production company. I can teach you Adobe Premiere Pro. I\'m looking to get better at photography.',
    skillsToTeach: [{ ...SKILLS[13], proficiency: 3 }],
    skillsToLearn: [SKILLS[6]],
    matches: [{ userId: 5, status: 'in-progress' }],
    status: 'online',
    level: 5,
    xp: 20,
    badges: ['Video Editor', 'First Lesson', 'Curious Learner', 'Consistent'],
    streak: 5,
    verifiedSkills: [14],
  },
  {
    id: 26,
    name: 'Varun Grover',
    avatar: 'https://ui-avatars.com/api/?name=Varun+Grover&background=random&color=fff&size=200',
    bio: 'SEO specialist who can get you on the first page of Google. I\'d love to learn how to bake sourdough bread.',
    skillsToTeach: [{ ...SKILLS[19], proficiency: 2 }],
    skillsToLearn: [SKILLS[9]],
    matches: [],
    status: 'online',
    level: 7,
    xp: 50,
    badges: ['SEO Expert', 'First Lesson', 'Curious Learner'],
    streak: 3,
    verifiedSkills: [20],
  },
  {
      id: 27,
      name: 'Anand Kumar',
      avatar: 'https://ui-avatars.com/api/?name=Anand+Kumar&background=random&color=fff&size=200',
      bio: 'Lover of tea and knitting. I can teach you the basics of knitting. Looking to improve my public speaking for work.',
      skillsToTeach: [{ ...SKILLS[17], proficiency: 1 }],
      skillsToLearn: [SKILLS[8]],
      matches: [],
      status: 'offline',
      level: 2,
      xp: 20,
      badges: ['Newbie', 'First Lesson', 'Curious Learner'],
      streak: 0,
      verifiedSkills: []
  },
  {
      id: 28,
      name: 'Bhavana Singh',
      avatar: 'https://ui-avatars.com/api/?name=Bhavana+Singh&background=random&color=fff&size=200',
      bio: 'I can teach you how to make amazing Italian food. Looking to learn how to play guitar.',
      skillsToTeach: [{ ...SKILLS[3], proficiency: 2 }],
      skillsToLearn: [SKILLS[1]],
      matches: [{ userId: 1, status: 'in-progress', scheduledSession: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString() }],
      status: 'online',
      level: 4,
      xp: 30,
      badges: ['First Lesson', 'Curious Learner', 'Consistent'],
      streak: 3,
      verifiedSkills: [4]
  },
  {
      id: 29,
      name: 'Chetan Bhagat',
      avatar: 'https://ui-avatars.com/api/?name=Chetan+Bhagat&background=random&color=fff&size=200',
      bio: 'Journalist and creative writer. I can help you with your writing. I would love to learn how to take better photos.',
      skillsToTeach: [{ ...SKILLS[7], proficiency: 3 }],
      skillsToLearn: [SKILLS[6]],
      matches: [],
      status: 'online',
      level: 6,
      xp: 50,
      badges: ['Guru', 'Storyteller', 'First Lesson', 'Curious Learner'],
      streak: 7,
      verifiedSkills: [8]
  },
  {
      id: 30,
      name: 'Dia Mirza',
      avatar: 'https://ui-avatars.com/api/?name=Dia+Mirza&background=random&color=fff&size=200',
      bio: 'I can teach you French. Looking to learn about personal finance.',
      skillsToTeach: [{ ...SKILLS[12], proficiency: 2 }],
      skillsToLearn: [SKILLS[16]],
      matches: [],
      status: 'offline',
      level: 3,
      xp: 10,
      badges: ['First Lesson', 'Curious Learner'],
      streak: 1,
      verifiedSkills: []
  },
  {
      id: 31,
      name: 'Esha Gupta',
      avatar: 'https://ui-avatars.com/api/?name=Esha+Gupta&background=random&color=fff&size=200',
      bio: 'Expert gardener. I can help you with your garden. I would love to learn how to knit.',
      skillsToTeach: [{ ...SKILLS[18], proficiency: 3 }],
      skillsToLearn: [SKILLS[17]],
      matches: [],
      status: 'online',
      level: 5,
      xp: 80,
      badges: ['Polymath', 'Gardener', 'First Lesson', 'Curious Learner', 'Dedicated'],
      streak: 9,
      verifiedSkills: [19]
  },
  {
      id: 32,
      name: 'Farhan Akhtar',
      avatar: 'https://ui-avatars.com/api/?name=Farhan+Akhtar&background=random&color=fff&size=200',
      bio: 'I can run for a long time. I can teach you how to run. I want to learn how to play chess.',
      skillsToTeach: [{ ...SKILLS[8], proficiency: 1 }],
      skillsToLearn: [SKILLS[15]],
      matches: [],
      status: 'online',
      level: 1,
      xp: 90,
      badges: ['Newbie', 'First Lesson', 'Curious Learner'],
      streak: 0,
      verifiedSkills: []
  },
  {
      id: 33,
      name: 'Mira Kapoor',
      avatar: 'https://ui-avatars.com/api/?name=Mira+Kapoor&background=random&color=fff&size=200',
      bio: 'I love crafting and making things with my hands. I can teach you knitting and would love to learn React to build a site for my creations.',
      skillsToTeach: [{ ...SKILLS[17], proficiency: 2 }],
      skillsToLearn: [SKILLS[0]],
      matches: [{ userId: 1, status: 'in-progress', scheduledSession: getTodayAtTime(16, 30) }],
      status: 'online',
      level: 1,
      xp: 15,
      badges: ['Newbie'],
      streak: 0,
      verifiedSkills: []
  },
  {
      id: 99,
      name: 'Admin User',
      avatar: 'https://ui-avatars.com/api/?name=Admin&background=random&color=fff&size=200',
      bio: 'I am the administrator of this platform.',
      skillsToTeach: [],
      skillsToLearn: [],
      matches: [],
      status: 'online',
      level: 99,
      xp: 100,
      badges: ['Platform Guardian'],
      streak: 999,
      verifiedSkills: [],
      isAdmin: true,
  },
];

export const MOCK_MESSAGES: Record<number, Message[]> = {
  2: [
    { id: 1, senderId: 2, receiverId: 1, text: "Hey Aditi! I saw we matched. Your React skills are exactly what I need for my recipe blog.", timestamp: "2023-10-27T10:00:00Z" },
    { id: 2, senderId: 1, receiverId: 2, text: "Hi Rohan! Awesome. And I've been dying to learn how to make proper pasta. This is a perfect match!", timestamp: "2023-10-27T10:01:00Z", reaction: '🎉' },
    { id: 3, senderId: 2, receiverId: 1, text: "Great! When are you free to chat about it?", timestamp: "2023-10-27T10:02:00Z" },
  ],
  4: [
    { id: 4, senderId: 4, receiverId: 1, text: "Hi! I see you're looking for data science help. I'd love to learn some photography.", timestamp: "2023-10-27T11:00:00Z" },
  ],
  17: [
    { id: 5, senderId: 17, receiverId: 1, text: "Hey Aditi, saw you wanted to learn some French. I can help with that!", timestamp: "2023-11-01T14:00:00Z" },
    { id: 6, senderId: 1, receiverId: 17, text: "Salut Divya! That would be amazing. I've always wanted to learn. Happy to trade for some React lessons.", timestamp: "2023-11-01T14:05:00Z", reaction: '👍' },
  ],
  18: [
      { id: 7, senderId: 18, receiverId: 19, text: "Hi Sita, your French skills are impressive. I'm a marketing expert, let's connect!", timestamp: "2023-11-02T09:30:00Z" }
  ],
  21: [
      { id: 8, senderId: 3, receiverId: 21, text: "Ishita, your chess skills are just what I was looking for. I can teach you Data Science in return.", timestamp: "2023-11-03T18:00:00Z" },
      { id: 9, senderId: 21, receiverId: 3, text: "Priya, that's a deal! Let's schedule something.", timestamp: "2023-11-03T18:10:00Z" }
  ],
};

export const MOCK_POSTS: Post[] = [
    { id: 1, authorId: 4, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'Just learned a new riff on the guitar! Who wants to learn it with me? 🎸 #guitar #music', likes: 125, comments: 12 },
    { id: 2, authorId: 2, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'The perfect sourdough loaf doesn\'t exi-- 😍. So proud of this one! #baking #sourdough', likes: 340, comments: 28 },
    { id: 3, authorId: 5, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'Golden hour is magic hour for portraits. Here\'s a shot from my latest session. #photography #portraits', likes: 210, comments: 19 },
    { id: 4, authorId: 1, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'Working on a new component library in React. The developer experience is 🔥. #reactdev #coding', likes: 450, comments: 55 },
    { id: 5, authorId: 17, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'Finding peace and balance with a morning yoga session. #yoga #mindfulness', likes: 180, comments: 15 },
    { id: 6, authorId: 21, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'A beautiful checkmate from my game last night. Always learning! #chess #strategy', likes: 95, comments: 8 },
    { id: 7, authorId: 23, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'My little urban garden is thriving! Fresh herbs for days. #gardening #urbanjungle', likes: 250, comments: 22 },
    { id: 8, authorId: 25, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'Experimenting with some new color grading techniques. What do you think? #videoediting #premierepro', likes: 155, comments: 14 },
    { id: 9, authorId: 18, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'Just launched a successful SEO campaign for a client. The results are incredible! #digitalmarketing #seo', likes: 310, comments: 35 },
    { id: 10, authorId: 31, thumbnailUrl: 'https://placehold.co/600x400/EEE/31343C?text=Skill+Clip', caption: 'Propagating some succulents today. It\'s amazing to watch them grow. #plants #gardening', likes: 190, comments: 18 },
];

export const MOCK_PRODUCTS: Product[] = [
    { id: 1, name: 'Professional React Hooks Course', imageUrl: 'https://placehold.co/200x200/EEE/31343C?text=Product', price: '$49.99', skillId: 1, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE1' },
    { id: 2, name: 'Acoustic Guitar Starter Pack', imageUrl: 'https://placehold.co/200x200/EEE/31343C?text=Product', price: '$129.99', skillId: 2, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE2' },
    { id: 3, name: 'Authentic Pasta Making Kit', imageUrl: 'https://placehold.co/200x200/EEE/31343C?text=Product', price: '$39.99', skillId: 4, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE3' },
    { id: 4, name: 'Sourdough Starter Kit', imageUrl: 'https://placehold.co/200x200/EEE/31343C?text=Product', price: '$24.99', skillId: 10, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE4' },
    { id: 5, name: 'DSLR Camera for Beginners', imageUrl: 'https://placehold.co/200x200/EEE/31343C?text=Product', price: '$499.99', skillId: 7, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE5' },
    { id: 6, name: 'Yoga Mat and Block Set', imageUrl: 'https://placehold.co/200x200/EEE/31343C?text=Product', price: '$34.99', skillId: 12, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE6' },
    { id: 7, name: 'Video Editing Software Suite', imageUrl: 'https://placehold.co/200x200/EEE/31343C?text=Product', price: '$99.99', skillId: 14, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE7' },
    { id: 8, name: 'Beginner\'s Knitting Set', imageUrl: 'https://placehold.co/200x200/EEE/31343C?text=Product', price: '$19.99', skillId: 18, amazonUrl: 'https://amazon.com/dp/B0EXAMPLE8' },
];